### ISSUE TITLE
内部测试服务镜像拉取问题

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-console#18]
目前，内部的测试服务器无法拉取`docker.io`镜像。需要:

1. 将hyperledgerk8s下镜像同步到内部镜像仓库
2. 修改前端默认镜像仓库为内部镜像仓库

**Comment by bjwswang** [comment]
需同步的镜像列表为:
- hyperledgerk8s/fabric-operator:latest
- hyperledgerk8s/ubi-minimal:latest 
- hyperledgerk8s/fabric-ca:iam-20230131
- hyperledgerk8s/fabric-peer:2.4.7 hyperledgerk8s/fabric-peer:2.4.7
- hyperledgerk8s/couchdb:3.2.2 hyperledgerk8s/fabric-orderer:2.4.7
- hyperledgerk8s/fabric-console:latest hyperledgerk8s/grpc-web:latest

**Comment by bjwswang** [comment]
@dayuy  需要配置镜像地址的地方包括:
- 组织创建: https://github.com/bestchains/fabric-operator/blob/main/config/samples/orgs/org1.yaml#L19
```yaml
  caSpec:
    license:
      accept: true
    ingress:
      class: "portal-ingress"
    images:
      caImage: hyperledgerk8s/fabric-ca
      caTag: "iam-20230131"
      caInitImage: hyperledgerk8s/ubi-minimal
      caInitTag: latest
```

- 网络创建 https://github.com/bestchains/fabric-operator/blob/main/config/samples/ibp.com_v1beta1_network.yaml
修改`networkSpec.orderSpec.images`如下:
```yaml
  images:
    ordererInitImage: hyperledgerk8s/ubi-minimal
    ordererInitTag: latest
    grpcwebImage: hyperledgerk8s/grpc-web
    grpcwebTag: latest
    ordererImage: hyperledgerk8s/fabric-orderer
    ordererTag: v2.4.7

```

- 节点创建 https://github.com/bestchains/fabric-operator/blob/main/config/samples/peers/ibp.com_v1beta1_peer_org1peer1.yaml
修改 `peerSpec` 下的
```yaml
peerSpec:
    images:
         peerInitImage: hyperledgerk8s/ubi-minimal
         peerInitTag: latest
         grpcwebImage: hyperledgerk8s/grpc-web
         grpcwebTag: latest
         peerImage: hyperledgerk8s/fabric-peer
         peerTag:  v2.4.7
```
